config/routes.rb
Rails.application.routes.draw do
  get 'orders/:id/payment', to: "orders#payment", as: "order_payment"
  resources :order_lines
  devise_scope :admin do
    authenticated :admin do
      get 'my_orderlist', to: "orders#my_orderlist", as: :my_orderlist
		  resources :products
		  resources :cashiers
		  resources :reports
      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_scope :cashier do
    authenticated :cashier do
      resources :orders
      # resources :order_lines
      post 'order_summary', to: "orders#order_summary", as: "order_summary"
      # resources :cashiers
      root 'cashiers#home', as: :authenticated_cashier
    end
  end
  
  devise_for :cashiers
  devise_for :admins
  root 'publics#index'
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :cashier
    has_many :order_lines#, inverse_of: :product
    accepts_nested_attributes_for :order_lines, 
    reject_if: :all_blank, allow_destroy: true
    
    
    after_create :compute_total_price

    private 

   	def compute_total_price
   		total_price = 0
   		self.order_lines.each do |lines|
   			total_price += lines.price
   		end

   		self.update_attributes(:total_price => total_price)
   	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  def index
    @orders = Order.all
  end
  
  def my_orderlist
    @orders = []
    @revenue = 0.0
    current_admin.cashiers.each do |cashier|
      cashier.orders.each do |order|
        @orders << order
        @revenue += order.total_price
        # return @orders.sort_by { |r| r[orders.id] }
      end
    end
  end
  
  def order_summary
    @order = current_cashier.orders.new(order_params)
    
    tp = 0
    @order.order_lines.each do |c|
    tp += c.product.price * c.quantity
    end
    
    @order.total_price = tp
  end
  
  def new
    @order = current_cashier.orders.new
  end
  
  def create
    @order = current_cashier.orders.new(order_params)

    tp = 0
    @order.order_lines.each do |c|
    tp += c.product.price * c.quantity
    end
    
    @order.total_price = tp
    
    if @order.save
      redirect_to order_path(@order), notice: "Order successfully created."
    else
      render :new
    end
  end
  
  def destroy
    @order.destroy
    redirect_to orders_path
  end
  
  # def destroy
  #   if @order.status == true
  #     @order.status = false
  #   else
  #     @order.status = true
  #   end
    
  #   if @order.save
  #     redirect_to orders_path, notice: "Order successfully updated."
  #   end
  # end
  
  def edit
  end
  
  def update
    if @order.update(order_params)
      redirect_to order_order_lines_path(@order), notice: "Order paid successfully."
    else
      render :edit
    end
  end
  
  # def update
  #   if @order.update(order_params)
  #     redirect_to orders_path, notice: "Order successfully updated."
  #   else
  #     render :edit
  #   end
  # end
  
  def payment
    @order_lines = @order.order_lines
  end
  
  def show
    @order = Order.find_by(id: params[:id])
    
    @change = @order.cash.to_s.to_d - @order.total_price.to_s.to_d
    
    if !@order.present?
      redirect_to orders_path
    end
  end
  
  private
    def order_params
      params.require(:order).permit!
    end
    
    def set_order
      @order = Order.find_by(id: params[:id])
      redirect_to orders_path, notice: "Order not found." if @order.nil?
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_confirm_form.html.erb
<%= simple_form_for @order, url: orders_path do |f| %>
    <% if @order.errors.any? %>
    <% @order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
    
    <div id="order_lines">
        <%= f.simple_fields_for :order_lines do |o| %>
          <%= render 'confirm_order_line_fields', f: o %>
        <% end %>
    </div>
    <br> 
    <%= f.button :submit, "Confirm order" %>
<% end %>

app/views/orders/_confirm_order_line_fields.html.erb
<div class="nested-fields">
        <table class="table table-hover">
            <thead>
                <th>Product</th>
                <th>Quantity</th>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <!--</%= f.select(:product_id, Product.where(status: true).collect{|f| [f.name]}, {}, :style => "width:500px") %>-->
                        <%= f.association :product, :as => :collection_select, collection: Product.where(status: true),  :label => "" %>
                    </td>
                    <td><%= f.number_field :quantity, min: 1, :style => "width:500px" %></td>
                    
                </tr>
            </tbody>
        </table>
</div>

app/views/orders/_form.html.erb
<%= simple_form_for @order, url: order_summary_path do |f| %>
    <% if @order.errors.any? %>
    <% @order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
    
    <div id="order_lines">
        <%= f.simple_fields_for :order_lines do |o| %>
          <%= render 'order_line_fields', f: o %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add Product', f, :order_lines, class: 'btn btn-info'  %>
        </div>
    </div>
    <br> 
    <%= f.button :submit %>
<% end %>

app/views/orders/_order_line_fields.html.erb
<div class="nested-fields">
        <table class="table table-hover">
            <thead class = "order_head_text">
                <th>Product</th>
                <th>Quantity</th>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <%= f.association :product, :as => :collection_select, collection: Product.where(status: true), :label => "" %>
                    </td>
                    <td><%= f.input :quantity, input_html: {min: '1', value: f.object.quantity || '1'} %></td>
                    <td><%= link_to_remove_association "Remove", f, class: 'btn btn-danger btn-sm' %></td>
                </tr>
            </tbody>
        </table>
</div>

app/views/orders/_payment_form.html.erb
<%= simple_form_for @order, url: order_path do |f| %>
    <% if @order.errors.any? %>
    <% @order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
    
    <div id="order_lines">
        <%= f.number_field :cash, min: 1 %>
    </div>
    <br> 
    <%= f.button :submit, "Pay" %>
<% end %>

app/views/orders/_show_list.html.erb
<table class="table table-hover">
    <thead class = "order_head_text">
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Sub Total</th>
    </thead>
    <tbody>
        <% @order.order_lines.each do |c| %>
            <tr>
                <td><%= c.product.name %></td>
                <td>₱ <%= c.product.price %></td>
                <td><%= c.quantity %></td>
                <% subtotal = c.quantity * c.product.price %>
                <td>₱ <%= subtotal %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/orders/edit.html.erb
<%= link_to 'Back', orders_path, class:"btn btn-primary btn-sm" %>

<hr>
<h1>Update Order</h1>

<%= render 'form', order: @order %>

app/views/orders/index.html.erb
<h1 class="orders_text">Orders</h1>
<hr>
<div class = "new_order_button">
<%= link_to "New Order", new_order_path, class: "btn btn-success btn-lg" %>
</div>
<br><br>
<% if @orders && @orders.empty? %>
<br>
<br>
    <small>
        <br>
<br>
<br>
        <em>No orders to show.</em>
    </small>
<% else %>
    <table class="table table-hover">
        <thead class="order_index_head">
            <th>ID</th>
            <th>Cashier</th>
            <th>Total</th>
            <th>Cash</th>
            <th>Order</th>
            <th colspan="2"></th>
        </thead>
        <tbody>
            <% @orders.each do |c| %>
                <tr>
                    <td><%= c.id %></td>
                    <td><%= c.cashier.name %></td>
                    <td>₱ <%= c.total_price %></td>
                    <td>₱ <%= c.cash %></td>
                    <td>
                        <% c.order_lines.each do |o| %>
                            <li><%= o.quantity %> - <%= o.product.name %></li>
                        <% end %>
                    </td>
                    <td><%= link_to 'Show', order_path(c), class: "btn btn-primary" %>
                    <!--<td><#%= link_to "Delete", -->
                    <!--            order_path(c.id),-->
                    <!--            method: :delete, -->
                    <!--            data: { confirm: "Are you sure you want to delete?" }, -->
                    <!--            class: 'btn btn-danger' %>-->
                    <!--</td>-->
                    <% if c.cash.nil? %>
                    
                    <td><%= link_to 'Pay', order_payment_path(c), class: "btn btn-success" %></td>
                    
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/orders/my_orderlist.html.erb
<h1 class = "list_index_header">Orders List</h1>
<hr>
<% if @orders.empty? %>
    <small>
        <em>No orders are made.</em>
    </small>
<% else %>
<h3>Total Revenue: ₱ <%= @revenue %></h3>
    <table class="table table-hover">
            <thead>
                <th>Order ID</th>
                <th>Order Date</th></th>
                <th>Total Price</th>
            </thead>
            <tbody>
            <% @orders.each do |c| %>
            <tr>
                <td><%= c.id %></td>
                <td><%= c.created_at %></td>
                <td>₱ <%= c.total_price %></td>
            </tr>
            <% end %>
            </tbody>
    </table>
<% end %>

app/views/orders/new.html.erb
<%= link_to 'Back', orders_path, class:"btn btn-primary btn-sm" %>  

<hr>
<h1 class = "new_order_text">New Order</h1>
<br>


<%= render 'form', order_line: @order_line %>

app/views/orders/order_summary.html.erb
<%= link_to 'Back', orders_path, class:"btn btn-primary btn-sm" %>  

<hr>
<h1 class = "order_text">Confirm Order</h1>
<br>
<%= render 'show_list', order_line: @order_line %>
<h2 class = "order_text">Total:  ₱<%= @order.total_price %></h2>
<br>
<div class="hidden">
    <%= simple_form_for @order, url: orders_path do |f| %>
        <div id="order_lines">
            <%= f.simple_fields_for :order_lines do |o| %>
              <%= render 'order_line_fields', f: o %>
            <% end %>
        </div>
</div>

<%= f.input :cash %>
<br>
<%= f.button :submit %>

<% end %>

app/views/orders/payment.html.erb
<div style="max-width: 500px; padding: 15px; margin: 0 auto;">
  <h1 style="text-align: center;">Ordering System</h1>
  <% unless @order.cash.nil? %>
    <h2 style="text-align: center;">Official Receipt</h2>
  <% end %>
  <h3 style="text-align: center;">Order: <%= @order.id %></h3>

  <p>
    <strong>Cashier:</strong>
    <%= @order.cashier.email %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= @order.cash.nil? ? "Not Paid" : "Paid" %>
  </p>


  <table class="table">
    <tbody>
      <% @order_lines.each do |order_line| %>
      <tr>
        <td><%= order_line.quantity %></td>
        <td><%= order_line.product.name %></td>
        <td>₱ <%= order_line.price %></td>
      </tr>
      <% end %>
    </tbody>

  </table>


  <hr>
  <p>
    <strong>Total: ₱ </strong>
    <%= @order.total_price %>
  </p>
<div>

<%= render 'payment_form', order: @order %>

app/views/orders/show.html.erb
<head runat="server">
    <title>Print Page</title>
    <script type="text/javascript">
        function print_page() {
            var ButtonControl = document.getElementById("btnprint");
            ButtonControl.style.visibility = "hidden";
            // var ButtonControl = document.getElementById("btnback");
            // ButtonControl.style.visibility = "hidden";
            window.print();
        }
    </script>
</head>

<!--</%= link_to 'Back', orders_path, class:"btn btn-primary btn-sm", id: "btnback"  %>-->

<h1>Order Summary</h1>

<%= render 'show_list', order_line: @order_line %>

<h2>Total:  ₱ <%= @order.total_price %></h2>
<h2>Cash:  ₱ <%= @order.cash %></h2>
<h2>Change:  ₱ <%= @change %></h2>
<br>
<input class="btn btn-warning" type="button" id="btnprint" value="Print" onclick="print_page()" />