config/routes.rb
Rails.application.routes.draw do
  get 'orders/:id/payment', to: "orders#payment", as: "order_payment"
  resources :order_lines
  devise_scope :admin do
    authenticated :admin do
      get 'my_orderlist', to: "orders#my_orderlist", as: :my_orderlist
		  resources :products
		  resources :cashiers
		  resources :reports
      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_scope :cashier do
    authenticated :cashier do
      resources :orders
      # resources :order_lines
      post 'order_summary', to: "orders#order_summary", as: "order_summary"
      # resources :cashiers
      root 'cashiers#home', as: :authenticated_cashier
    end
  end
  
  devise_for :cashiers
  devise_for :admins
  root 'publics#index'
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :admin
  has_many :orders
  
  # def to_s
  #   "#{email}"
  # end
  
  def active_for_authentication?
        logger.debug self.to_yaml 	
        super && status?
  end
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
    before_action :set_cashier, only: [:update, :edit, :destroy, :show]

  # def my_cashiers
  #   @cashiers = current_admin.cashiers
  # end
  
  def index
    @cashiers = Cashier.all
  end
  
  def new
    @cashier = current_admin.cashiers.new
  end
  
  def create
    @cashier = current_admin.cashiers.new(cashier_params)
    @cashier.status = true
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully added."
    else
      render :new
    end
  end
  
  def destroy
    if @cashier.status == true
      @cashier.status = false
    else
      @cashier.status = true
    end
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    end
  end
  
  def edit
  end
  
  def update
    if @cashier.update(cashier_params)
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    else
      render :edit
    end
  end
  
  def show
  end
  
  private
    def cashier_params
      params.require(:cashier).permit!
    end
    
    def set_cashier
      @cashier = Cashier.find_by(id: params[:id])
      redirect_to cashiers_path, notice: "Cashier not found." if @cashier.nil?
    end
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/views/cashiers/_form.html.erb
<%= form_for cashier do |f| %>

  <% if @cashier.errors.any? %>
  <br>
  <div class="col-md-offset-0 col-md-12">
    <div class="row">
    <div class="alert alert-danger">
        <h4>Sorry, could not proceed due to the following problems:</h4>
        <% @cashier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

    <br>
    <label>Name</label>
    <br>
    <%= f.text_field :name, autofocus: true %>
    <br>
    <label>Email</label>
    <br>
    <%= f.text_field :email, autofocus: true %>
    <br>
    <label>Password</label>
    <br>
    <%= f.password_field :password %>
    <br>
    <label>Confirm Password</label>
    <br>
    <%= f.password_field :password_confirmation %>
    <br>
    <br>
    <%= f.submit class: "btn btn-info btn-mini" %>
<% end %>

app/views/cashiers/edit.html.erb
<%= link_to 'Back', cashiers_path, class:"btn btn-primary btn-sm" %>

<hr>
<h1>Update Cashier</h1>

<%= render 'form', cashier: @cashier %>

app/views/cashiers/home.html.erb
    <h1>Welcome, <%= current_cashier.name %>!</h1>
    <!--<h1>Welcome, Cashier!</h1>-->
    <hr>

app/views/cashiers/index.html.erb
<h1 class = "cashier_index_header">Cashiers</h1>
<hr>
<div class = "cashier_button"> <%= link_to "Add Cashier", new_cashier_path, class: "btn btn-info btn-lg" %> </div>
<br><br>
<% if @cashiers.empty? %>
<br>
<br>
    <small>
        <em>No cashiers to show.</em>
    </small>
<% else %>
    <table class="table table-hover">
        <thead class="cashier_index_head">
            <th >Name</th>
            <th>Email</th>
            <th>Registered by</th>
            <th>Status</th>
            <th colspan="3"></th>
        </thead>
        <tbody>
            <% @cashiers.each do |c| %>
                <tr class="<%= c.status ? 'warning' : 'active' %>">
                    <td><%= c.name %></td>
                    <td><%= c.email %></td>
                    <td>
                    <%= c.admin.email %>
                    </td>
                    <td>
                        <%= c.status ? "Active" : "Inactive" %>
                    </td>
                    <td>
                        <%= link_to "View Cashier", cashier_path(c), class: 'btn btn-primary' %>
                        <%= link_to "Edit", edit_cashier_path(c), class: 'btn btn-warning' %>
                        <% if c.status %>
                            <%= link_to "Deactivate", 
                                cashier_path(c.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to deactivate?" }, class: 'btn btn-danger' %>
                        <% else %>
                            <%= link_to "Activate", 
                                cashier_path(c.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to activate?" }, class: 'btn btn-success' %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/cashiers/new.html.erb
<%= link_to 'Back', cashiers_path, class:"btn btn-primary btn-sm" %>  

<hr>
<h1>New Cashier</h1>

<%= render 'form', cashier: @cashier %>

app/views/cashiers/show.html.erb
<div class="col-md-offset-3 col-md-6">
    <div class="row">
        <div class="col-xs-6">
            <%= link_to 'Back', cashiers_path, class:"btn btn-primary btn-sm"  %>
        </div>
        <div class="col-xs-6">
            <span class="pull-right">
            <%= link_to 'Edit', edit_cashier_path, class:"btn btn-warning btn-sm" %>
            
            <% if @cashier.status == true %>
                <%= link_to "Deactivate", 
                                cashier_path(@cashier.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to deactivate?" }, class: 'btn btn-danger btn-sm' %>
            <% else %>
                <%= link_to "Activate",
                                cashier_path(@cashier.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to activate?" }, class: 'btn btn-success btn-sm' %>
            <% end %>
            </span>
            <br>
        </div>
        </div>

        <hr>
        <h3>Cashier Details</h3>
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td> <strong> Cashier Name: </strong> </td>
                    <td><%= @cashier.name %></td>
                </tr>
                <tr>
                    <td> <strong> Email: </strong> </td>
                    <td> <%= @cashier.email %> </td>
                </tr>
                <tr>
                    <td> <strong> Registered by: </strong> </td>
                    <td> <%= @cashier.admin.email %> </td>
                </tr>
                <tr>
                    <td> <strong> Status: </strong> </td>
                    
                    <% if @cashier.status == true %>
                    <td> <%= "Active"  %> </td>
                    <% else %>
                    <td> <%= "Inactive" %> </td>
                    <% end %>
                </tr>
            </tbody>
        </table>

<br>
    <h3>View Orders</h3>
    <div class="row">
        <table class= "table table-hover">
            <thead>
                <th>Order ID</th>
                <th>Order Date</th></th>
                <th>Total Price</th>
            </thead>
            <tbody>
            <% @cashier.orders.each do |c| %>
            <tr>
                <td><%= c.id %></td>
                <td><%= c.created_at %></td>
                <td>₱ <%= c.total_price %></td>
            </tr>
        <% end %>
            </tbody>
        </table>
    </div>
</div>