config/routes.rb
Rails.application.routes.draw do
  get 'orders/:id/payment', to: "orders#payment", as: "order_payment"
  resources :order_lines
  devise_scope :admin do
    authenticated :admin do
      get 'my_orderlist', to: "orders#my_orderlist", as: :my_orderlist
		  resources :products
		  resources :cashiers
		  resources :reports
      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_scope :cashier do
    authenticated :cashier do
      resources :orders
      # resources :order_lines
      post 'order_summary', to: "orders#order_summary", as: "order_summary"
      # resources :cashiers
      root 'cashiers#home', as: :authenticated_cashier
    end
  end
  
  devise_for :cashiers
  devise_for :admins
  root 'publics#index'
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_lines
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:update, :edit, :destroy, :show]

  # def my_products
  #   @products = current_admin.products
  # end
  
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.status = true
    
    if @product.save
      redirect_to products_path, notice: "Product successfully added."
    else
      render :new
    end
  end
  
  def destroy
    if @product.status == true
      @product.status = false
    else
      @product.status = true
    end
    
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    end
  end
  
  def edit
  end
  
  def update
    if @product.update(product_params)
      redirect_to products_path, notice: "Product successfully updated."
    else
      render :edit
    end
  end
  
  def show
  end
  
  private
    def product_params
      params.require(:product).permit!
    end
    
    def set_product
      @product = Product.find_by(id: params[:id])
      redirect_to products_path, notice: "Product not found." if @product.nil?
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for product do |f| %>
    <label>Name</label>
    <br>
    <%= f.text_field :name %>
    <br>
    
    <label>Price</label>
    <br>
    <!--</%= f.number_field :price %>-->
    <%= f.number_field :price, class: :text_field, step: :any %>
    <br>
    <br>
    <%= f.submit class: "btn btn-info btn-mini" %>
<% end %>

app/views/products/edit.html.erb
<%= link_to 'Back', products_path, class:"btn btn-primary btn-sm" %>  

<hr>
<h1>Update Product</h1>
<br>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1 class = "product_index_header">Products</h1>
<hr>
<div class = "product_button"> <%= link_to "Add Product", new_product_path, class: "btn btn-info btn-lg" %> </div>
<br><br>
<% if @products.empty? %>
<br>
<br>
    <small>
        <em>No products to show.</em>
    </small>
<% else %>
    <table class="table table-hover">
        <thead>
            <th class="product_index_head">Name</th>
            <th class="product_index_head">Price</th>
            <th class="product_index_head">Status</th>
            <th colspan="3"></th>
        </thead>
        <tbody>
            <% @products.each do |p| %>
                <tr class="<%= p.status ? 'warning' : 'active' %>">
                    <td><%= p.name %></td>
                    <td>₱ <%= p.price %></td>
                    <td>
                        <%= p.status ? "Active" : "Inactive" %>
                    </td>
                    <td>
                        <%= link_to "View Product", product_path(p), class: 'btn btn-primary' %>
                        <%= link_to "Edit", edit_product_path(p), class: 'btn btn-warning' %>
                        <% if p.status %>
                            <%= link_to "Deactivate", 
                                product_path(p.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to deactivate?" }, class: 'btn btn-danger' %>
                        <% else %>
                            <%= link_to "Activate", 
                                product_path(p.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to activate?" }, class: 'btn btn-success' %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/products/new.html.erb
<%= link_to 'Back', products_path, class:"btn btn-primary btn-sm" %>  

<hr>
<h1>New Product</h1>
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<div class="col-md-offset-3 col-md-6">
    <div class="row">
        <div class="col-xs-6">
            <%= link_to 'Back', products_path, class:"btn btn-primary btn-sm"  %>
        </div>
        <div class="col-xs-6">
            <span class="pull-right">
            <%= link_to 'Edit', edit_product_path, class:"btn btn-warning btn-sm" %>
            
            <% if @product.status == true %>
                <%= link_to "Deactivate", 
                                product_path(@product.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to deactivate?" }, class: 'btn btn-danger btn-sm' %>
            <% else %>
                <%= link_to "Activate",
                                product_path(@product.id),
                                method: :delete, 
                                data: { confirm: "Are you sure you want to activate?" }, class: 'btn btn-success btn-sm' %>
            <% end %>
            </span>
            <br>
        </div>
        </div>

        <hr>
        <h3>Product Details</h3>
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td> <strong> Product Name: </strong> </td>
                    <td><%= @product.name %></td>
                </tr>
                <tr>
                    <td> <strong> Price: </strong> </td>
                    <td>₱ <%= @product.price %> </td>
                </tr>
                <tr>
                    <td> <strong> Status: </strong> </td>
                    
                    <% if @product.status == true %>
                    <td> <%= "Active"  %> </td>
                    <% else %>
                    <td> <%= "Inactive" %> </td>
                    <% end %>
                    
                </tr>
            </tbody>
        </table>
    </div>
</div>