config/routes.rb
Rails.application.routes.draw do
  get 'orders/:id/payment', to: "orders#payment", as: "order_payment"
  resources :order_lines
  devise_scope :admin do
    authenticated :admin do
      get 'my_orderlist', to: "orders#my_orderlist", as: :my_orderlist
		  resources :products
		  resources :cashiers
		  resources :reports
      root 'admins#index', as: :authenticated_admin
    end
  end
  
  devise_scope :cashier do
    authenticated :cashier do
      resources :orders
      # resources :order_lines
      post 'order_summary', to: "orders#order_summary", as: "order_summary"
      # resources :cashiers
      root 'cashiers#home', as: :authenticated_cashier
    end
  end
  
  devise_for :cashiers
  devise_for :admins
  root 'publics#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :cashiers
  
  def to_s
    "#{email}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :admin
  has_many :orders
  
  # def to_s
  #   "#{email}"
  # end
  
  def active_for_authentication?
        logger.debug self.to_yaml 	
        super && status?
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_save :compute_total_price,
  			  :descrease_total_stock
  after_save :recompute_orders
  after_destroy :recompute_orders
  before_destroy :increase_total_stock

  validates :quantity, presence: true,
  					   numericality: { greater_than: 0 }

  private

  def compute_total_price
  	self.price = self.product.price * self.quantity
  end

  def descrease_total_stock
  	self.product.update_attributes(stock_items: (self.product.stock_items-self.quantity))
  end

  def increase_total_stock
  	self.product.update_attributes(stock_items: (self.product.stock_items+self.quantity))
  end

  def recompute_orders
  	total = self.order.compute_total
  	item_total = self.order.compute_item_total
  	self.order.update_attributes(total: total, item_total: item_total)
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :cashier
    has_many :order_lines#, inverse_of: :product
    accepts_nested_attributes_for :order_lines, 
    reject_if: :all_blank, allow_destroy: true
    
    
    after_create :compute_total_price

    private 

   	def compute_total_price
   		total_price = 0
   		self.order_lines.each do |lines|
   			total_price += lines.price
   		end

   		self.update_attributes(:total_price => total_price)
   	end
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
    belongs_to :order, required: false
    belongs_to :product
    
    before_save :compute_price

    private

    def compute_price
    	self.price = self.quantity * self.product.price
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_lines
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
#   @daily = get_reports(LineItem.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day))
  end
  
  private

  def get_reports(line_item)
  	top_ten = []
  	products = Product.all
  	products.each do |p| 
  		number_of_buyers = 0
  		line_item.each do |i|  
  			if p.id == i.product_id
  				number_of_buyers += 1 
  			end
  		end
  		top_ten.push({:id => p.id, :name => p.name, :rating => number_of_buyers})
  	end
  	return top_ten.sort_by { |r| r[:rating] }.reverse.take(10)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  def index
    @orders = Order.all
  end
  
  def my_orderlist
    @orders = []
    @revenue = 0.0
    current_admin.cashiers.each do |cashier|
      cashier.orders.each do |order|
        @orders << order
        @revenue += order.total_price
        # return @orders.sort_by { |r| r[orders.id] }
      end
    end
  end
  
  def order_summary
    @order = current_cashier.orders.new(order_params)
    
    tp = 0
    @order.order_lines.each do |c|
    tp += c.product.price * c.quantity
    end
    
    @order.total_price = tp
  end
  
  def new
    @order = current_cashier.orders.new
  end
  
  def create
    @order = current_cashier.orders.new(order_params)

    tp = 0
    @order.order_lines.each do |c|
    tp += c.product.price * c.quantity
    end
    
    @order.total_price = tp
    
    if @order.save
      redirect_to order_path(@order), notice: "Order successfully created."
    else
      render :new
    end
  end
  
  def destroy
    @order.destroy
    redirect_to orders_path
  end
  
  # def destroy
  #   if @order.status == true
  #     @order.status = false
  #   else
  #     @order.status = true
  #   end
    
  #   if @order.save
  #     redirect_to orders_path, notice: "Order successfully updated."
  #   end
  # end
  
  def edit
  end
  
  def update
    if @order.update(order_params)
      redirect_to order_order_lines_path(@order), notice: "Order paid successfully."
    else
      render :edit
    end
  end
  
  # def update
  #   if @order.update(order_params)
  #     redirect_to orders_path, notice: "Order successfully updated."
  #   else
  #     render :edit
  #   end
  # end
  
  def payment
    @order_lines = @order.order_lines
  end
  
  def show
    @order = Order.find_by(id: params[:id])
    
    @change = @order.cash.to_s.to_d - @order.total_price.to_s.to_d
    
    if !@order.present?
      redirect_to orders_path
    end
  end
  
  private
    def order_params
      params.require(:order).permit!
    end
    
    def set_order
      @order = Order.find_by(id: params[:id])
      redirect_to orders_path, notice: "Order not found." if @order.nil?
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    
	def index
	    @daily = get_reports(OrderLine.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day))
	  	@weekly = get_reports(OrderLine.where(created_at: Date.today.beginning_of_week..Date.today.end_of_week))
	  	@monthly = get_reports(OrderLine.where(created_at: Date.today.beginning_of_month..Date.today.end_of_month))
	end

	private

	def get_reports(order_lines)
		top_ten = []
		products = Product.all
		products.each do |p| 
			number_of_buyers = 0
			qeach = 0
			order_lines.each do |o|  
				if p.id == o.product_id
					number_of_buyers += 1
					qeach += o.quantity
				end
			end
			unless number_of_buyers.zero?
				top_ten.push({:id => p.id, :name => p.name, :rating => number_of_buyers, :quantityeach => qeach})
			end
		end
		return top_ten.sort_by { |r| r[:quantityeach] }.reverse.take(10)
	end
	
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    attr_writer :resource
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/admins/index.html.erb
    <!--<h1>Welcome, </%= "Admin!" %></h1>-->
    <% x = current_admin.name %>
    <h1> Welcome, <%= x %>!</h1> 
    <!--#No Admin name yet-->
    <hr>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if admin_signed_in? %>
            <%= link_to "POS System", authenticated_admin_path, class: "navbar-brand" %>
          <% elsif cashier_signed_in? %>
            <%= link_to "POS System", authenticated_cashier_path, class: "navbar-brand" %>
          <% else %>
            <%= link_to "POS System", root_path, class: "navbar-brand" %>
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if admin_signed_in? %>
              <li>
                <%= link_to "Cashiers", cashiers_path %>
              </li>
              <li>
                <%= link_to "Products", products_path %>
              </li>
              <li>
                <%= link_to "Reports", reports_path %>
              </li>
              <li>
                <%= link_to "Orders List", my_orderlist_path %>
              </li>
            <% elsif cashier_signed_in? %>
              <li>
                <%= link_to "Orders", orders_path %>
              </li>
            <% end %>
            <!--<li class="active"><a href="/ideas">Ideas</a></li>-->
          </ul>
          <p class="navbar-text pull-right">
            <% if admin_signed_in? %>
              Logged in as <strong><%= current_admin.email %></strong>|
              <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
            <% elsif cashier_signed_in? %>
              Logged in as <strong><%= current_cashier.email %></strong>|
              <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>
            <% end %>
            </p>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
  
      <%= yield %>
    </div>
  </body>
</html>